### ISSUE TITLE
bam2tags failure: /tmp Disk quota exceeded

### ISSUE THREAD

**Issue by olegs** [JetBrains-Research/washu#15] opened 2017-10-02 08:54 UTC
```
bam2tags OD_OD1_H3K27ac_unique.bam 150
sort: write failed: /tmp/3464929.mgt2.cluster/sort4DlXUO: Disk quota exceeded
awk: (FILENAME=- FNR=727299) fatal: print to "standard output" failed (Broken pipe)
```

**Comment by olegs** [comment] 2017-10-02 10:42
It looks like we should pay more attention to `sort` tmp folders.

**Comment by olegs** [comment] 2017-10-02 13:41
We see lots of failures:
```
[oshpynov@login01 chipseq_analysis]$ find . -name "*.log" | xargs grep -i -e "exception"
./configs/Y20O20/peaks/H3K27ac/OD_OD13_H3K27ac_zinbra_hg19.log:java.nio.file.FileSystemException: /tmp/simd876852749934419666: Disk quota exceeded
./configs/Y20O20/peaks/H3K27ac/OD_OD13_H3K27ac_zinbra_hg19.log:	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
./configs/Y20O20/peaks/H3K27ac/OD_OD13_H3K27ac_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
./configs/Y20O20/peaks/H3K27ac/OD_OD13_H3K27ac_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
./configs/Y20O20/peaks/H3K27me3/OD_OD12_H3K27me3_zinbra_hg19.log:java.nio.file.FileSystemException: /tmp/simd2184047188640798954: Disk quota exceeded
./configs/Y20O20/peaks/H3K27me3/OD_OD12_H3K27me3_zinbra_hg19.log:	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
./configs/Y20O20/peaks/H3K27me3/OD_OD12_H3K27me3_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
./configs/Y20O20/peaks/H3K27me3/OD_OD12_H3K27me3_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
./configs/Y20O20/peaks/H3K4me1/OD_OD10_H3K4me1_zinbra_hg19.log:java.nio.file.FileSystemException: /tmp/simd7681246267938449430: Disk quota exceeded
./configs/Y20O20/peaks/H3K4me1/OD_OD10_H3K4me1_zinbra_hg19.log:	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
./configs/Y20O20/peaks/H3K4me1/OD_OD10_H3K4me1_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
./configs/Y20O20/peaks/H3K4me1/OD_OD10_H3K4me1_zinbra_hg19.log:	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
./configs/Y20O20/unique/H3K27ac/OD_OD20_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Disk quota exceeded
./configs/Y20O20/unique/H3K27ac/OD_OD20_H3K27ac_unique.log:Caused by: java.io.IOException: Disk quota exceeded
./configs/Y20O20/unique/H3K27ac/YD_YD10_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1263150174829002007.tmp
./configs/Y20O20/unique/H3K27ac/OD_OD9_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2549878480852125229.tmp
./configs/Y20O20/unique/k27me3_old/OD_OD13_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7281522012015751707.tmp
./configs/Y20O20/unique/k27me3_old/OD_input_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.8281645860631078848.tmp
./configs/Y20O20/unique/k27me3_old/OD_OD8_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.9031419587617115757.tmp
./configs/Y20O20/unique/k27me3_old/YD_input_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.4955948373122896926.tmp
./configs/Y20O20/unique/k27me3_old/OD_OD19_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2473972220830823826.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD3_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1287164705606284852.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD16_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5968007829475015553.tmp
./configs/Y20O20/unique/k4me3_old/YD_YD8_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7759780347051942025.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD10_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7722539814166558598.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD1_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1568318442504961116.tmp
./configs/Y20O20/unique/k4me3_old/OD_input_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.3856037940163985063.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD9_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5287892258631626593.tmp
./configs/Y20O20/unique/k4me3_old/YD_YD6_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1123848701788992211.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD15_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2314787662116445826.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD8_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7206688319626325687.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD19_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.868760114660799452.tmp
./configs/Y20O20/unique/k4me3_old/OD_OD18_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1202314776974327745.tmp
./configs/Y20O20/unique/k4me3_old/YD_YD11_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.4139938456240134288.tmp
./configs/Y20O20/unique/k4me3_old/YD_YD19_H3K4me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.6911737611644599898.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/OD_OD20_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5010697994800281163.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/YD_YD18_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.3468012862515427004.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/OD_OD6_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.6365313414159990737.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/YD_YD6_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5727857145221625215.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/OD_OD4_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2923298511411298212.tmp
./configs/Y20O20/unique/H3K27me3_tmp8743914623699489841/YD_YD19_H3K27me3_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7792882392497897709.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD16_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.4748912608226335586.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD9_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7594861519363359663.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD11_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1438125034172174784.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD18_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5758398256712628341.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD9_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.128612564057349359.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD5_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.4408937118445740953.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD4_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.394506119311052941.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD19_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.4406691112780591056.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD6_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2509992703447693952.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD18_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.1536379287406053038.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD10_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2847027484169245969.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD5_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5199838218435274791.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD19_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5803925847827316705.tmp
./configs/Y20O20/unique/k4me1_old/YD_input_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.3979244037777007785.tmp
./configs/Y20O20/unique/k4me1_old/OD_OD14_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.2082310268343331302.tmp
./configs/Y20O20/unique/k4me1_old/YD_YD17_H3K4me1_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.3388338442353528029.tmp
./configs/Y20O20/unique/K27ac_old/YD_YD7_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5560149481725787905.tmp
./configs/Y20O20/unique/K27ac_old/OD_OD12_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.8343345245319194147.tmp
./configs/Y20O20/unique/K27ac_old/YD_YD21_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.7543883856111941523.tmp
./configs/Y20O20/unique/K27ac_old/OD_OD15_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.8771024915114582679.tmp
./configs/Y20O20/unique/K27ac_old/YD_YD2_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.6143743386705166189.tmp
./configs/Y20O20/unique/K27ac_old/OD_OD16_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.544447103247400275.tmp
./configs/Y20O20/unique/K27ac_old/OD_OD3_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.8480454110859913783.tmp
./configs/Y20O20/unique/K27ac_old/YD_YD4_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.3148352033358079772.tmp
./configs/Y20O20/unique/K27ac_old/OD_OD9_H3K27ac_unique.log:Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.5174577915080081107.tmp
```

**Comment by iromeo** [comment] 2017-10-02 14:07
>  `htsjdk.samtools.SAMException: Could not create temporary directory /tmp/CSPI.*`
I've fixed picard.jar usage to use customized tmp dir

**Comment by iromeo** [comment] 2017-10-02 14:10
AFAIU the only usage of `bam2tags` is `chipseq_diff.sh`
I recommend you to vectorize places like:
```
   run_parallel << SCRIPT
#!/bin/sh
#PBS -N O_bam2tags
#PBS -l nodes=1:ppn=1,walltime=24:00:00,vmem=8gb
#PBS -j oe
#PBS -o ${CHIPDIFF}/O_bams2tags.log
# This is necessary because qsub default working dir is user home
cd ${CHIPDIFF}
module load bedtools2
for F in ${READS_O}; do
    >&2 echo \$F
    bash ${SCRIPT_DIR}/scripts/bam2tags.sh \$F $SHIFT_O >> O_tags.tag
done
SCRIPT
```
to multiple QSUB tasks per each file. You'll get performance boost and less TMPDIR load

**Comment by olegs** [comment] 2017-10-02 14:48
We still errors with picard.jar
```
[oshpynov@login01 H3K27ac_tmp4884856722201224430]$ cat OD_OD12_H3K27ac_unique.log
--------------------------------------------------------------
Begin PBS Prologue Mon Oct  2 09:46:17 CDT 2017 1506955577
Job ID:			3481979.mgt2.cluster
Username:		oshpynov
Group:			martyomov
Nodes:			gpu09
End PBS Prologue Mon Oct  2 09:46:17 CDT 2017 1506955577
--------------------------------------------------------------
Picked up _JAVA_OPTIONS: -Xmx12g
09:46:18.209 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/scratch/artyomov_lab_aging/chipseq_analysis/configs/Y20O20/unique/H3K27ac_tmp4884856722201224430/picard.jar!/com/intel/gkl/native/libgkl_compression.so
09:46:18.223 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (Disk quota exceeded)
09:46:18.224 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/scratch/artyomov_lab_aging/chipseq_analysis/configs/Y20O20/unique/H3K27ac_tmp4884856722201224430/picard.jar!/com/intel/gkl/native/libgkl_compression.so
09:46:18.224 WARN  NativeLibraryLoader - Unable to load libgkl_compression.so from native/libgkl_compression.so (Disk quota exceeded)
[Mon Oct 02 09:46:18 CDT 2017] MarkDuplicates INPUT=[OD_OD12_H3K27ac.bam] OUTPUT=OD_OD12_H3K27ac_unique.bam METRICS_FILE=OD_OD12_H3K27ac_metrics.txt REMOVE_DUPLICATES=true    MAX_SEQUENCES_FOR_DISK_READ_ENDS_MAP=50000 MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=8000 SORTING_COLLECTION_SIZE_RATIO=0.25 TAG_DUPLICATE_SET_MEMBERS=false REMOVE_SEQUENCING_DUPLICATES=false TAGGING_POLICY=DontTag CLEAR_DT=true ASSUME_SORTED=false DUPLICATE_SCORING_STRATEGY=SUM_OF_BASE_QUALITIES PROGRAM_RECORD_ID=MarkDuplicates PROGRAM_GROUP_NAME=MarkDuplicates READ_NAME_REGEX=<optimized capture of last three ':' separated fields as numeric values> OPTICAL_DUPLICATE_PIXEL_DISTANCE=100 MAX_OPTICAL_DUPLICATE_SET_SIZE=300000 ADD_PG_TAG_TO_READS=true VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Mon Oct 02 09:46:18 CDT 2017] Executing as oshpynov@gpu09 on Linux 2.6.32-642.11.1.el6.centos.plus.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_40-b26; Deflater: Jdk; Inflater: Jdk; Picard version: 2.12.1-SNAPSHOT
INFO	2017-10-02 09:46:18	MarkDuplicates	Start of doWork freeMemory: 2006375784; totalMemory: 2025848832; maxMemory: 11453595648
INFO	2017-10-02 09:46:18	MarkDuplicates	Reading input file and constructing read end information.
INFO	2017-10-02 09:46:18	MarkDuplicates	Will retain up to 41498534 data points before spilling to disk.
09:46:18.384 WARN  IntelDeflaterFactory - IntelInflater is not supported, using Java.util.zip.Inflater
WARNING	2017-10-02 09:46:18	SamFiles	The index file /scratch/artyomov_lab_aging/Y20O20/chipseq/processed/k27ac/k27ac_20vs20_redo_bams/OD12_k27ac_hg19.bam.bai was found by resolving the canonical path of a symlink: /scratch/artyomov_lab_aging/chipseq_analysis/configs/Y20O20/unique/H3K27ac_tmp4884856722201224430/OD_OD12_H3K27ac.bam -> /scratch/artyomov_lab_aging/Y20O20/chipseq/processed/k27ac/k27ac_20vs20_redo_bams/OD12_k27ac_hg19.bam
[Mon Oct 02 09:46:18 CDT 2017] picard.sam.markduplicates.MarkDuplicates done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=2025848832
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/3481979.mgt2.cluster/CSPI.8518873774469239343.tmp
	at htsjdk.samtools.util.IOUtil.createTempDir(IOUtil.java:774)
	at htsjdk.samtools.CoordinateSortedPairInfoMap.<init>(CoordinateSortedPairInfoMap.java:59)
	at picard.sam.markduplicates.util.DiskBasedReadEndsForMarkDuplicatesMap.<init>(DiskBasedReadEndsForMarkDuplicatesMap.java:57)
	at picard.sam.markduplicates.MarkDuplicates.buildSortedReadEndLists(MarkDuplicates.java:483)
	at picard.sam.markduplicates.MarkDuplicates.doWork(MarkDuplicates.java:232)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:268)
	at picard.cmdline.PicardCommandLine.instanceM--------------------------------------------------------------
Begin PBS Epilogue Mon Oct  2 09:46:23 CDT 2017 1506955583
Job ID:			3481979.mgt2.cluster
Username:		oshpynov
Group:			martyomov
Job Name:		unique_H3K27ac_tmp4884856722201224430_OD_OD12_H3K27ac
Limits:           	neednodes=1:ppn=4,nodes=1:ppn=4,vmem=32gb,walltime=24:00:00
Resources:		cput=00:00:00,energy_used=0,mem=0kb,vmem=0kb,walltime=00:00:01
Nodes:	        	gpu09
End PBS Epilogue Mon Oct  2 09:46:23 CDT 2017 1506955583
```

**Comment by iromeo** [comment] 2017-10-02 16:23
`Exception in thread "main" htsjdk.samtools.SAMException: Could not create temporary directory /tmp/3481979.mgt2.cluster/CSPI.8518873774469239343.tmp`

No idea, I've manage to successfully create `/tmp/$PBS_JOBID/CSPI.8518873774469239343.tmp` folder in interactive session, not clear why it failed in picard tools

**Comment by PetrTsurinov** [comment] 2018-09-24 14:59
This was a Washu High Performance Computing system specific problem, cannot reproduce anymore, closing.

**Closed by PetrTsurinov** 2018-09-24 14:59 UTC
Labels: bug
