### ISSUE TITLE
Macs2LogsTest.test_process_macs2_logs test is flaky

### ISSUE THREAD

**Issue by iromeo** [JetBrains-Research/washu#11] opened 2017-09-06 12:03 UTC
See buildserver results. Tests fails for no reason from time to time

**Comment by iromeo** [comment] 2017-09-13 19:51
@olegs please verify this fix

**Comment by olegs** [comment] 2018-09-24 16:03
Test was removed, closing as cannot reproduce.

**Closed by olegs** 2018-09-24 16:03 UTC
